### ISSUE TITLE
Edit timeslots rules is NOT possible

### ISSUE THREAD

**Issue by BreakSecurity** [thoughtco/ti-ext-maxorders#1]
**Expected behavior:**
After rule creation I I should be able to edit and save it.

**Actual behavior:**
After rule creation, every things worked until I tried to edit it. The following error rises:
 `ErrorException: Trying to get property 'order_date' of non-object
in /home/info/domains/info.info/public_html/setup-master/extensions/igniter/local/listeners/MaxOrderPerTimeslotReached.php:42
Stack trace:
#0 /home/info/domains/info.info/public_html/setup-master/extensions/igniter/local/listeners/MaxOrderPerTimeslotReached.php(42): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Trying to get p...', '/home/info...', 42, Array)
#1 [internal function]: Igniter\Local\Listeners\MaxOrderPerTimeslotReached->Igniter\Local\Listeners\{closure}('19:30:00', '2020-10-25')
#2 /home/info/domains/info.info/public_html/setup-master/vendor/laravel/framework/src/Illuminate/Support/Arr.php(643): array_filter(Array, Object(Closure), 1)
#3 /home/info/domains/info.info/public_html/setup-master/vendor/laravel/framework/src/Illuminate/Support/Collection.php(352): Illuminate\Support\Arr::where(Array, Object(Closure))
#4 /home/info/domains/info.info/public_html/setup-master/extensions/igniter/local/listeners/MaxOrderPerTimeslotReached.php(45): Illuminate\Support\Collection->filter(Object(Closure))
#5 [internal function]: Igniter\Local\Listeners\MaxOrderPerTimeslotReached->timeslotValid(Object(Igniter\Flame\Location\WorkingSchedule), Object(Carbon\Carbon))
#6 /home/info/domains/info.info/public_html/setup-master/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(388): call_user_func_array(Array, Array)
#7 /home/info/domains/info.info/public_html/setup-master/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(218): Illuminate\Events\Dispatcher->Illuminate\Events\{closure}('igniter.working...', Array)
#8 /home/info/domains/info.info/public_html/setup-master/vendor/tastyigniter/flame/src/Events/Dispatcher.php(17): Illuminate\Events\Dispatcher->dispatch('igniter.working...', Array, true)
#9 /home/info/domains/info.info/public_html/setup-master/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Igniter\Flame\Events\Dispatcher->fire('igniter.working...', Array, true)
#10 /home/info/domains/info.info/public_html/setup-master/vendor/tastyigniter/flame/src/Location/WorkingSchedule.php(443): Illuminate\Support\Facades\Facade::__callStatic('fire', Array)
#11 [internal function]: Igniter\Flame\Location\WorkingSchedule->Igniter\Flame\Location\{closure}(Object(Carbon\Carbon), 1603650600)
#12 /home/info/domains/info.info/public_html/setup-master/vendor/laravel/framework/src/Illuminate/Support/Arr.php(643): array_filter(Array, Object(Closure), 1)
#13 /home/info/domains/info.info/public_html/setup-master/vendor/laravel/framework/src/Illuminate/Support/Collection.php(352): Illuminate\Support\Arr::where(Array, Object(Closure))
#14 /home/info/domains/info.info/public_html/setup-master/vendor/tastyigniter/flame/src/Location/WorkingSchedule.php(446): Illuminate\Support\Collection->filter(Object(Closure))
#15 /home/info/domains/info.info/public_html/setup-master/vendor/tastyigniter/flame/src/Location/WorkingSchedule.php(334): Igniter\Flame\Location\WorkingSchedule->filterTimeslot(Object(Illuminate\Support\Collection), Object(Carbon\Carbon))
#16 /home/info/domains/info.info/public_html/setup-master/extensions/igniter/local/classes/Location.php(249): Igniter\Flame\Location\WorkingSchedule->getTimeslot(Object(DateInterval), Object(Carbon\Carbon), Object(DateInterval))
#17 /home/info/domains/info.info/public_html/setup-master/extensions/igniter/local/components/LocalBox.php(219): Igniter\Local\Classes\Location->scheduleTimeslot()
#18 /home/info/domains/info.info/public_html/setup-master/extensions/igniter/local/components/LocalBox.php(131): Igniter\Local\Components\LocalBox->prepareVars()
#19 /home/info/domains/info.info/public_html/setup-master/app/main/template/concerns/HasComponents.php(102): Igniter\Local\Components\LocalBox->onRun()
#20 /home/info/domains/info.info/public_html/setup-master/app/main/classes/MainController.php(304): Main\Template\Model->runComponents()
#21 /home/info/domains/info.info/public_html/setup-master/app/main/classes/MainController.php(263): Main\Classes\MainController->execPageCycle()
#22 /home/info/domains/info.info/public_html/setup-master/app/main/classes/MainController.php(199): Main\Classes\MainController->runPage(Object(Main\Template\Page))
#23 /home/info/domains/info.info/public_html/setup-master/app/system/classes/Controller.php(85): Main\Classes\MainController->remap('default/menus')
#24 [internal function]: System\Classes\Controller->run('default/menus')
#25 /home/info/domains/info.info/public_html/setup-master/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#26 /home/info/domains/info.info/public_html/setup-master/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction('run', Array)
#27 /home/info/domains/info.info/public_html/setup-master/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(System\Classes\Controller), 'run')
#28 /home/info/domains/info.info/public_html/setup-master/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\Routing\Route->runController()
#29 /home/info/domains/info.info/public_html/setup-master/vendor/laravel/framework/src/Illuminate/Routing/Router.php(681): Illuminate\Routing\Route->run()
#30 /home/info/domains/info.info/public_html/setup-master/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#31 /home/info/domains/info.info/public_html/setup-master/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(77): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#32 /home/info/domains/info.info/public_html/setup-master/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#33 /home/info/domains/info.info/public_html/setup-master/vendor/tastyigniter/flame/src/Currency/Middleware/CurrencyMiddleware.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#34 /home/info/domains/info.info/public_html/setup-master/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Igniter\Flame\Currency\Middleware\CurrencyMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#35 /home/info/domains/info.info/public_html/setup-master/extensions/igniter/cart/middleware/CartMiddleware.php(12): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#36 /home/info/domains/info.info/public_html/setup-master/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Igniter\Cart\Middleware\CartMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#37 /home/info/domains/info.info/public_html/setup-master/vendor/tastyigniter/flame/src/Translation/Middleware/Localization.php(40): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#38 /home/info/domains/info.info/public_html/setup-master/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Igniter\Flame\Translation\Middleware\Localization->handle(Object(Illuminate\Http\Request), Object(Closure))
#39 /home/info/domains/info.info/public_html/setup-master/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#40 /home/info/domains/info.info/public_html/setup-master/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#41 /home/info/domains/info.info/public_html/setup-master/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#42 /home/info/domains/info.info/public_html/setup-master/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#43 /home/info/domains/info.info/public_html/setup-master/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(56): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#44 /home/info/domains/info.info/public_html/setup-master/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#45 /home/info/domains/info.info/public_html/setup-master/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#46 /home/info/domains/info.info/public_html/setup-master/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#47 /home/info/domains/info.info/public_html/setup-master/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#48 /home/info/domains/info.info/public_html/setup-master/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#49 /home/info/domains/info.info/public_html/setup-master/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#50 /home/info/domains/info.info/public_html/setup-master/vendor/laravel/framework/src/Illuminate/Routing/Router.php(683): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#51 /home/info/domains/info.info/public_html/setup-master/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#52 /home/info/domains/info.info/public_html/setup-master/vendor/laravel/framework/src/Illuminate/Routing/Router.php(624): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
#53 /home/info/domains/info.info/public_html/setup-master/vendor/october/rain/src/Router/CoreRouter.php(20): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#54 /home/info/domains/info.info/public_html/setup-master/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(170): October\Rain\Router\CoreRouter->dispatch(Object(Illuminate\Http\Request))
#55 /home/info/domains/info.info/public_html/setup-master/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#56 /home/info/domains/info.info/public_html/setup-master/vendor/tastyigniter/flame/src/Setting/Middleware/SaveSetting.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#57 /home/info/domains/info.info/public_html/setup-master/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Igniter\Flame\Setting\Middleware\SaveSetting->handle(Object(Illuminate\Http\Request), Object(Closure))
#58 /home/info/domains/info.info/public_html/setup-master/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#59 /home/info/domains/info.info/public_html/setup-master/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#60 /home/info/domains/info.info/public_html/setup-master/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#61 /home/info/domains/info.info/public_html/setup-master/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#62 /home/info/domains/info.info/public_html/setup-master/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#63 /home/info/domains/info.info/public_html/setup-master/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle(Object(Illuminate\Http\Request), Object(Closure))
#64 /home/info/domains/info.info/public_html/setup-master/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#65 /home/info/domains/info.info/public_html/setup-master/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#66 /home/info/domains/info.info/public_html/setup-master/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#67 /home/info/domains/info.info/public_html/setup-master/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#68 /home/info/domains/info.info/public_html/setup-master/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#69 /home/info/domains/info.info/public_html/setup-master/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#70 {main}`

**Reproduce steps:**
Create one rule for a specific timeslot, save it, try to edit it.

**Version:**
v.3.0.4-beta.23.2

**Additional Information:**
![immagine](https://user-images.githubusercontent.com/38836022/97119808-045db680-1713-11eb-91ef-a9bd2763fa2b.png)

**Comment by ryanmitchell** [comment]
This one is a bug in the local extension which has already been fixed here:
https://github.com/tastyigniter/ti-ext-local/commit/5ca6dea56c5ff6abdfb9bae52e509c21b4a898d4

**Comment by BreakSecurity** [comment]
Since it is solved I will close this issue thanks
