### ISSUE TITLE
Extension crash

### ISSUE THREAD

**Issue by BreakSecurity** [thoughtco/ti-ext-maxorders#2]
**Expected behavior:**
No "randoms" crash

**Actual behavior:**
After rule creation, I added 3 new limitations. The following error rises:
 `ErrorException: Invalid argument supplied for foreach()
in /home/info/domains/info.info/public_html/setup-master/extensions/thoughtco/maxorders/models/config/timeslots.php:46
Stack trace:
#0 /home/info/domains/info.info/public_html/setup-master/extensions/thoughtco/maxorders/models/config/timeslots.php(46): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'Invalid argumen...', '/home/info...', 46, Array)
#1 [internal function]: Illuminate\Filesystem\Filesystem->{closure}(Object(Thoughtco\Maxorders\Models\Timeslots), Object(Admin\Classes\ListColumn), NULL)
#2 /home/info/domains/info.info/public_html/setup-master/app/admin/widgets/Lists.php(646): call_user_func_array(Object(Closure), Array)
#3 /home/info/domains/info.info/public_html/setup-master/storage/framework/views/1a3c95790e776ee6c9c92b19126eeee509666b0a.php(38): Admin\Widgets\Lists->getColumnValue(Object(Thoughtco\Maxorders\Models\Timeslots), Object(Admin\Classes\ListColumn))
#4 /home/info/domains/info.info/public_html/setup-master/app/system/traits/ViewMaker.php(227): include('/home/info...')
#5 /home/info/domains/info.info/public_html/setup-master/app/system/traits/ViewMaker.php(189): Admin\Classes\BaseWidget->makeFileContent('/home/info...', Array)
#6 /home/info/domains/info.info/public_html/setup-master/storage/framework/views/98d024ca67c6533277081449daabc3a9f1a77e4e.php(16): Admin\Classes\BaseWidget->makePartial('lists/list_body')
#7 /home/info/domains/info.info/public_html/setup-master/app/system/traits/ViewMaker.php(227): include('/home/info...')
#8 /home/info/domains/info.info/public_html/setup-master/app/system/traits/ViewMaker.php(189): Admin\Classes\BaseWidget->makeFileContent('/home/info...', Array)
#9 /home/info/domains/info.info/public_html/setup-master/app/admin/widgets/Lists.php(178): Admin\Classes\BaseWidget->makePartial('lists/list')
#10 /home/info/domains/info.info/public_html/setup-master/app/admin/actions/ListController.php(282): Admin\Widgets\Lists->render()
#11 [internal function]: Admin\Actions\ListController->renderList()
#12 /home/info/domains/info.info/public_html/setup-master/vendor/tastyigniter/flame/src/Traits/ExtendableTrait.php(428): call_user_func_array(Array, Array)
#13 /home/info/domains/info.info/public_html/setup-master/vendor/tastyigniter/flame/src/Support/Extendable.php(42): Igniter\Flame\Support\Extendable->extendableCall('renderList', Array)
#14 /home/info/domains/info.info/public_html/setup-master/storage/framework/views/6b17da5fc88859933f009cf624606d7b7dea5aff.php(2): Igniter\Flame\Support\Extendable->__call('renderList', Array)
#15 /home/info/domains/info.info/public_html/setup-master/app/system/traits/ViewMaker.php(227): include('/home/info...')
#16 /home/info/domains/info.info/public_html/setup-master/app/system/traits/ViewMaker.php(152): Admin\Classes\AdminController->makeFileContent('/home/info...')
#17 /home/info/domains/info.info/public_html/setup-master/app/admin/classes/AdminController.php(210): Admin\Classes\AdminController->makeView('index')
#18 /home/info/domains/info.info/public_html/setup-master/app/admin/classes/AdminController.php(172): Admin\Classes\AdminController->execPageAction('index', Array)
#19 /home/info/domains/info.info/public_html/setup-master/app/system/classes/Controller.php(111): Admin\Classes\AdminController->remap('index', Array)
#20 [internal function]: System\Classes\Controller->runAdmin('thoughtco/maxor...')
#21 /home/info/domains/info.info/public_html/setup-master/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#22 /home/info/domains/info.info/public_html/setup-master/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction('runAdmin', Array)
#23 /home/info/domains/info.info/public_html/setup-master/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(System\Classes\Controller), 'runAdmin')
#24 /home/info/domains/info.info/public_html/setup-master/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\Routing\Route->runController()
#25 /home/info/domains/info.info/public_html/setup-master/vendor/laravel/framework/src/Illuminate/Routing/Router.php(681): Illuminate\Routing\Route->run()
#26 /home/info/domains/info.info/public_html/setup-master/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#27 /home/info/domains/info.info/public_html/setup-master/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(77): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#28 /home/info/domains/info.info/public_html/setup-master/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#29 /home/info/domains/info.info/public_html/setup-master/vendor/tastyigniter/flame/src/Currency/Middleware/CurrencyMiddleware.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#30 /home/info/domains/info.info/public_html/setup-master/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Igniter\Flame\Currency\Middleware\CurrencyMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#31 /home/info/domains/info.info/public_html/setup-master/app/admin/middleware/LogUserLastSeen.php(26): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#32 /home/info/domains/info.info/public_html/setup-master/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Admin\Middleware\LogUserLastSeen->handle(Object(Illuminate\Http\Request), Object(Closure))
#33 /home/info/domains/info.info/public_html/setup-master/vendor/tastyigniter/flame/src/Translation/Middleware/Localization.php(40): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#34 /home/info/domains/info.info/public_html/setup-master/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Igniter\Flame\Translation\Middleware\Localization->handle(Object(Illuminate\Http\Request), Object(Closure))
#35 /home/info/domains/info.info/public_html/setup-master/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#36 /home/info/domains/info.info/public_html/setup-master/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#37 /home/info/domains/info.info/public_html/setup-master/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#38 /home/info/domains/info.info/public_html/setup-master/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#39 /home/info/domains/info.info/public_html/setup-master/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(56): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#40 /home/info/domains/info.info/public_html/setup-master/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#41 /home/info/domains/info.info/public_html/setup-master/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#42 /home/info/domains/info.info/public_html/setup-master/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#43 /home/info/domains/info.info/public_html/setup-master/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#44 /home/info/domains/info.info/public_html/setup-master/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#45 /home/info/domains/info.info/public_html/setup-master/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#46 /home/info/domains/info.info/public_html/setup-master/vendor/laravel/framework/src/Illuminate/Routing/Router.php(683): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#47 /home/info/domains/info.info/public_html/setup-master/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#48 /home/info/domains/info.info/public_html/setup-master/vendor/laravel/framework/src/Illuminate/Routing/Router.php(624): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
#49 /home/info/domains/info.info/public_html/setup-master/vendor/october/rain/src/Router/CoreRouter.php(20): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#50 /home/info/domains/info.info/public_html/setup-master/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(170): October\Rain\Router\CoreRouter->dispatch(Object(Illuminate\Http\Request))
#51 /home/info/domains/info.info/public_html/setup-master/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#52 /home/info/domains/info.info/public_html/setup-master/vendor/tastyigniter/flame/src/Setting/Middleware/SaveSetting.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#53 /home/info/domains/info.info/public_html/setup-master/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Igniter\Flame\Setting\Middleware\SaveSetting->handle(Object(Illuminate\Http\Request), Object(Closure))
#54 /home/info/domains/info.info/public_html/setup-master/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#55 /home/info/domains/info.info/public_html/setup-master/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#56 /home/info/domains/info.info/public_html/setup-master/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#57 /home/info/domains/info.info/public_html/setup-master/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#58 /home/info/domains/info.info/public_html/setup-master/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#59 /home/info/domains/info.info/public_html/setup-master/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle(Object(Illuminate\Http\Request), Object(Closure))
#60 /home/info/domains/info.info/public_html/setup-master/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#61 /home/info/domains/info.info/public_html/setup-master/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#62 /home/info/domains/info.info/public_html/setup-master/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#63 /home/info/domains/info.info/public_html/setup-master/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#64 /home/info/domains/info.info/public_html/setup-master/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#65 /home/info/domains/info.info/public_html/setup-master/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#66 {main}`

**Reproduce steps:**
Create some rules, save them, move around dashboard.

**Version:**
v.3.0.4-beta.23.2

**Comment by ryanmitchell** [comment]
This extension is very much a work I progress. I haven’t released it yet or tested it for the marketplace.

**Comment by BreakSecurity** [comment]
Just trying to help

**Comment by ryanmitchell** [comment]
What values did you enter for the timeslots you set up? Seems like its erroring on the day(s) of the week value.

**Comment by BreakSecurity** [comment]
Select all for days

**Comment by ryanmitchell** [comment]
Send me a screenshot of the editing view I’ve tested that and it works ok for me so it must be something else.

**Comment by BreakSecurity** [comment]
A lot of changes was done on the extension and tasty since this bug that do NOT happen again.
