### ISSUE TITLE
The restriction affects ONLY the FIRST timeslot in the restriction interval

### ISSUE THREAD

**Issue by BreakSecurity** [thoughtco/ti-ext-maxorders#4]
If I set a limitation between 00:00 - 23:50 (all day) of n covers/orders/etc.. ONLY the FIRST timeslot is removed when the limit is reached. All the other timeslots remain unaffected by the restriction.

**Comment by ryanmitchell** [comment]
This is correct behaviour - I think you've misunderstood the intention of the time period.

It is not to count the orders in that time period, but to apply the restriction to any timeslots in that period.

So going by what you have said, the first timeslot is the one with orders in it, and is the only one with more orders than the maximum.

**Comment by BreakSecurity** [comment]
Ok I will be back after some new test. Thanks for the hint ;)

**Comment by BreakSecurity** [comment]
All good here too ;)
