### ISSUE TITLE
Invalid argument supplied for foreach(), models/config/timeslots.php:44

### ISSUE THREAD

**Issue by BreakSecurity** [thoughtco/ti-ext-maxorders#5]
**To reproduce:**
1) I set a limitation of 1 order selecting days, location, and times. I save and close.
2) I notice that I do not set the type of order so I open limitation again I set delivery as order type and I save again. The system ask me to select covers element too.
3) Since I do not want category limitation I go back without saving. Sys error:

```
ErrorException: Invalid argument supplied for foreach()
in /home/info/domains/info.info/public_html/d2clone/extensions/thoughtco/maxorders/models/config/timeslots.php:44 
```

**Comment by ryanmitchell** [comment]
Thanks, fixed here:
https://github.com/thoughtco/ti-ext-maxorders/commit/09bb89f87897410ba2b3028241fb7662c7ca841f

**Comment by BreakSecurity** [comment]
Testing right now ;)

**Comment by BreakSecurity** [comment]
**To reproduce:**
1) I set a limitation of 1 order of type delivery. I save and close.
2) I make a delivery order and then I change the status to received (my default status is NOT received).
3) If I want to make another order. Sys error:

```
ErrorException: Undefined property: stdClass::$order_type
in /home/info/domains/info.info/public_html/d2clone/extensions/thoughtco/maxorders/listeners/MaxOrders.php:102 
```

**Comment by BreakSecurity** [comment]
The limitation is applied to all statuses except completed and cancelled right?

**Comment by ryanmitchell** [comment]
This is an error on kitchen display, not max orders, i'll transfer the issue there.

**Comment by BreakSecurity** [comment]
Sorry wrong place

**Comment by BreakSecurity** [comment]
```
ErrorException: Undefined property: stdClass::$order_type
in /home/info/domains/info.info/public_html/d2clone/extensions/thoughtco/maxorders/listeners/MaxOrders.php:102 
```

**Comment by BreakSecurity** [comment]
Do not transfer I wrongly copy/pasted. NowI edit my comment

**Comment by ryanmitchell** [comment]
This should fix it: https://github.com/thoughtco/ti-ext-maxorders/commits/master

**Comment by BreakSecurity** [comment]
I will test again ;)

**Comment by BreakSecurity** [comment]
So if I have a restriction to max 1 order and I have 3 timeslot of 30 m

10:00 10:30 11:00

and I do 1 order for 10:30 that timeslot is removed... correct.
But if I change the parameters that generate the timeslots (for example I switch from delivery to pick-up or chenge the distance between the timslots) and the 10:30 timeslot is not present any more, another one is removed (NOT always the closest one).

**Comment by ryanmitchell** [comment]
Can you give me steps to reproduce with all settings please?

**Comment by BreakSecurity** [comment]
These are the parameters set to generate the timeslots
![immagine](https://user-images.githubusercontent.com/38836022/99522496-058ea600-2996-11eb-8a16-1ea6f481da95.png)
these are the timeslots that are generated
![immagine](https://user-images.githubusercontent.com/38836022/99522532-1212fe80-2996-11eb-8d2e-83060798cdb2.png)
I create this limitation of orders
![immagine](https://user-images.githubusercontent.com/38836022/99522577-22c37480-2996-11eb-9f58-176c948c78fc.png)
I make an order for 3:40pm
![immagine](https://user-images.githubusercontent.com/38836022/99522661-37a00800-2996-11eb-86c0-1cb4119e457c.png)
If I try to place another order, as expected, the 3:40 pm timeslot is hidden
![immagine](https://user-images.githubusercontent.com/38836022/99522716-47b7e780-2996-11eb-9122-97776ab76aa6.png)
At this point, I change the parameters that generate the timeslots again
![immagine](https://user-images.githubusercontent.com/38836022/99522772-5900f400-2996-11eb-9868-3b877b19c252.png)
I try to place an order again: the 3:40 pm timeslot is no longer generated; the 3:28 pm timeslot is removed in its place. If the closest were removed, the 3:45pm one would have to be cancelled I guess
![immagine](https://user-images.githubusercontent.com/38836022/99522976-b137f600-2996-11eb-894a-a883edefae8d.png)
I try to make a pickup order (with timeslots generated differently) and the problem is the same. Of the new timeslots, the 3:33 pm one is removed
![immagine](https://user-images.githubusercontent.com/38836022/99523028-c0b73f00-2996-11eb-998b-13e5d36b82c2.png)
I don't understand the criterion with which this happens. Restaurants often ask to change their hours during the evening, and I would like to understand better how it works.

**Comment by ryanmitchell** [comment]
Ok, for me this is correct behaviour, so I’ll try to explain :)

Think of the slots as a window of time with a start and end time.

So Wed 3.28pm until 3.44pm is the window that gets removed as the order you placed falls within that window.

Then 3.33 to 3.46 is removed as the order you placed falls within that window.

Does that help make sense of it?

**Comment by BreakSecurity** [comment]
Everything clear thanks. I think I have tested max-orders enough now I will switch to display kitchen V2.

Thanks for all the efforts @ryanmitchell
