### ISSUE TITLE
[Bug]: maxorder shows blank page tasty igniter is updated, using the latest one

### ISSUE THREAD

**Issue by shumailasiddique** [thoughtco/ti-ext-maxorders#9]
### What happened?

![maxorderbug](https://github.com/thoughtco/ti-ext-maxorders/assets/46244940/dfb69472-8f86-4266-8377-0e5d8db59a72)

### What did you expect to happen?

I expect to view some settings to mange orders limit 

### Version

3.7.5

### What browser are you seeing the problem on?

Chrome

### Relevant log output

```shell
no logs
```

**Comment by ryanmitchell** [comment]
This add-on is unsupported. Feel free to open a PR with the fixes if you wish to see it fixed.
